### PR TITLE
fix: reminder_perms not work with extra default_permissions

### PR DESCRIPTION
**Pull request by DemidovEvg**

### CODE REVIEW

**Comment by DemidovEvg** [comment]
Hello!
I use models permissions for turning off visibility models from app list:
```
class SomeModel(models.Model):
   class Meta(BaseMeta):
     permissions = [('can_see_in_app_list_somemodel', 'Can see SomeModel in app list')]
```
I have a lot of models like this.
But I think best desicion will be create base Meta like this:
```
class BaseMeta:
   default_permissions = ('add', 'change', 'delete', 'view', 'see_in_app_list')

class SomeModel(models.Model):
   class Meta(BaseMeta):
      pass
```
And django will automatically create permissions with verbose name and correct value.

**Comment by RamezIssac** [comment]
Hello 

Well, I never thought to use it like this _(nor i agree with the conclusion that it's better to be in the `default_permissions` rather than the `permissions` tbh)_
However, if it's made possible by Django, then it should be supported i believe.

Will revise and most probably merge , and will release soon anyway.
Thank you @DemidovEvg !

**Comment by SteMazzO** [comment]
Hello @RamezIssac, is there a scheduled date for the next release?

**Comment by RamezIssac** [comment]
Thank you @SteMazzO @DemidovEvg 

Released https://pypi.org/project/django-tabular-permissions/2.9.3/

**Pull request merged**
